# Generated by Django 4.1.1 on 2023-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_monthlybudget_year_alter_yearlybudget_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='track',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearlybudget',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
