# Generated by Django 4.1.1 on 2023-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_monthlybudget_track_yearlybudget_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybudget',
            name='track',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='yearlybudget',
            name='track',
            field=models.BooleanField(default=True),
        ),
    ]
