# Generated by Django 4.1.1 on 2022-12-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecurring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description: Optional')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost in USD')),
                ('start_date', models.DateField(verbose_name='Start Date of Recurring Expense')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Final Date of Recurring Expense')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Expected Times to Pay Recurring Expense')),
                ('cycle', models.IntegerField(choices=[(365, 'Daily'), (52, 'Weekly'), (365, 'Biweekly'), (365, 'Monthly'), (365, 'Quarterly'), (365, 'Semiannually'), (365, 'Annually')], default=12, verbose_name='Interval of Recurring Expense')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recurring_category', to='base.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseFixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description: Optional')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost in USD')),
                ('date', models.DateField(verbose_name='Date of Expense')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='fixed_category', to='base.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
