# Generated by Django 4.1.1 on 2022-12-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_fixedexpense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpense',
            name='date',
            field=models.DateField(verbose_name='Date of Expense'),
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description: Optional'),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description: Optional'),
        ),
    ]
