# Generated by Django 4.1.1 on 2023-01-05 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_fixedexpense_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description: Optional')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost in USD')),
                ('date', models.DateField(verbose_name='Date of Expense')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='all_expenses', to='base.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description: Optional')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Cost in USD')),
                ('start_date', models.DateField(verbose_name='Start Date of Recurring Expense')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Final Date of Recurring Expense')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Expected Times to Pay Recurring Expense')),
                ('cycle', models.IntegerField(choices=[(365, 'Daily'), (52, 'Weekly'), (26, 'Biweekly'), (12, 'Monthly'), (4, 'Quarterly'), (2, 'Semiannually'), (1, 'Annually')], default=12, verbose_name='Interval of Recurring Expense')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='all_subscriptions', to='base.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recurringexpense',
            name='user',
        ),
        migrations.DeleteModel(
            name='FixedExpense',
        ),
        migrations.DeleteModel(
            name='RecurringExpense',
        ),
    ]
