# Generated by Django 4.1.1 on 2023-01-09 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_expense_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yearlybudget',
            name='user',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_expenses', to='base.category'),
        ),
        migrations.DeleteModel(
            name='MonthlyBudget',
        ),
        migrations.DeleteModel(
            name='YearlyBudget',
        ),
    ]
