# Generated by Django 4.1.1 on 2023-02-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_expense_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Description: Optional'),
        ),
    ]
