# Generated by Django 4.1.1 on 2023-03-29 14:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_expense_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
