# Generated by Django 4.1.1 on 2023-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='relation',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Alcohol and tobacco', 'Alcohol and tobacco'), ('Housing and utilities', 'Housing and utilities'), ('Apparel and services', 'Apparel and services'), ('Transportation', 'Transportation'), ('Healthcare', 'Healthcare'), ('Entertainment', 'Entertainment'), ('Personal care', 'Personal care'), ('Reading', 'Reading'), ('Education', 'Education'), ('Miscellaneous', 'Miscellaneous'), ('Cash contributions', 'Cash contributions'), ('Personal insurance and pensions', 'Personal insurance and pensions')], default=None, max_length=40, null=True),
        ),
    ]
