# Generated by Django 4.1.1 on 2023-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='indefinite',
            field=models.BooleanField(blank=True, null=True, verbose_name='Check this box if you are unsure of when you plan on terminating the subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='terminated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
