# Generated by Django 4.1.1 on 2023-01-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_indefinite_subscription_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='indefinite',
            field=models.BooleanField(blank=True, null=True, verbose_name='Indefinite'),
        ),
    ]
