# Generated by Django 4.1.1 on 2023-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_terminated'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='terminated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
