# Generated by Django 4.1.1 on 2023-02-08 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_expense_subscription'),
        ('subscription', '0006_subscription_terminated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_subscriptions', to='base.category'),
        ),
    ]
